### ISSUE TITLE
数据库导入问题

### ISSUE THREAD

**Issue by flyingtango** [huruji/HopeLibrarySystem#1]
数据库导入时，出现如下问题

Batch file: /Users/van/Desktop/HopeLibrarySystem/hope_v2.sql
(2017-05-13 10:48:00) execution started
(2017-05-13 10:48:00) execution finished
went through 6 queries
3 errors encountered
Error at query 1: Invalid default value for 'bookCate'
Error at query 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE hopeReader(
readerID INT KEY AUTO_INCREMENT,
readerName VARCHAR(20)' at line 13
Error at query 6: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT hopeReader.readerName AS reader, COUNT(*) AS count FROM bookBorrow JOIN h' at line 2

是否 ENUM有问题呢？还是如何，望解答！

**Comment by huruji** [comment]
按照报错，总共有3个错误，其中第二个错误时由于缺少分号，第三个错误在于这个语句之前是自己统计时的测试语句，这两个我已经解决了，你可以下载新的sql文件，至于第一个我测试没有问题，你的mysql版本方便告知吗？

**Comment by flyingtango** [comment]
ok~第一个问题是由于没有把mysql设置为utf-8导致选择项可能有问题，这个我已经解决了。然后在下载了最新的sql文件并导入后。安装步骤配置config，输入node app 后显示listening port 3000，但是浏览器没有办法访问。我的系统是macOS 10.12.3。是否中间缺少了步骤，或者是我哪里疏忽了。node的安装没有问题。

**Comment by huruji** [comment]
config.js文件中的server对象下的port就是监听的端口，你看下这个是多少，改成3000试一下

**Comment by flyingtango** [comment]
ok 还有一个问题，起始时无注册页面，且数据表均为空表，我无法登陆。在尝试加入用户名，md5的密码后也无法登陆。想问下，如何才能登陆进系统呢？谢谢啦~~~

**Comment by huruji** [comment]
应该是可以登录的呀===

**Comment by flyingtango** [comment]
能否给个用户名的例子，比如 密码明文是什么 然后 数据库中存的是什么呢？试了好多次都不行
