### ISSUE TITLE
关于登陆账号

### ISSUE THREAD

**Issue by flyingtango** [huruji/HopeLibrarySystem#2]
抱歉 我试了很多次 还是未能成功 您能否给出几个具体的例子？比如明文是什么 数据库中存的是什么？
我试的为 明文：123456  md5：e10adc3949ba59abbe56e057f20f883e

**Comment by flyingtango** [comment]
能否导出测试时使用的数据库sql文件呢？各个表都为空看不懂字段该怎么设置。麻烦了！

**Comment by huruji** [comment]
使用的是md5，sql文件已经更新

**Comment by flyingtango** [comment]
好像需要将第一个插入改成
INSERT hopeReader VALUES(1,"忽如寄","8c0c831640c1da9f210e8951758aed5a","男","编程组","14234343","高分子材料与工程","1889999999","594613537@qq.com",0,"/img/user/user-default.jpg");
不然会显示插入的参数数量不对

**Comment by flyingtango** [comment]
8c0c831640c1da9f210e8951758aed5a  对应的原文是什么？是 “*hope8848”! 吗
